services:
  postgres:
    image: postgres:17-alpine
    container_name: fp_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fizyopark2024
      POSTGRES_DB: postgres
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_local_data:
